### ISSUE TITLE
Auto approve for cli commnds

### ISSUE THREAD

**Issue by ghost** [onelogin/onelogin#12]
Hi,

Thanks for the cli, we managed to use it to import our apps. For automation purposes we want to be able to auto approve the import commands but currently there's nothing in the readme or the `--help` message that indicates that this is possible.

Is there a way to do that?

**Comment by dcaponi** [comment]
Interesting, I'll see if we can bump this feature up. It should be really straightforward to implement and is already a planned improvement.

**Comment by dcaponi** [comment]
@AlaaMansour [This release](https://github.com/onelogin/onelogin/releases/tag/v0.0.4) should have what you need.

in 0.0.4 the help command should output this. You can use it like `onelogin terraform-import onelogin_apps --auto_approve`
```
Flags:
      --auto_approve   Skip confirmation of resource import
  -h, --help           help for terraform-import
      --id string      Import one resource by id
```

Please let me know if that works out by closing the issue.

**Comment by dcaponi** [comment]
Closing due to fix being shipped 3 days ago without issues :)
