### ISSUE TITLE
Terraform 0.13 support, issues with resources that share a name / start with a number

### ISSUE THREAD

**Issue by jbauers** [onelogin/onelogin#20]
Hey again! :smile:  As you can probably tell by now we've been playing around with the Terraform provider a lot. Trying the import this CLI provides, we ran into a few small issues I've bundled together here:

#### Terraform 0.13 support
As described [here](https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations), Terraform 0.13 changed the way providers work, and `terraform init` will fail with the current provider stanzas.

#### Resource names
We also ran into an issue where we had applications with the same name in the UI, which would fail the import due to duplicate resource names. Application names that start with a number would also fail the import.

---

I've ~fixed~ worked around these issues [here](https://github.com/onelogin/onelogin/compare/develop...jbauers:develop) by prepending a `_` to all resource names, appending the number, and changing the provider stanza. With these changes, the import succeeds and I can successfully run `terraform plan` after `onelogin terraform-import onelogin_apps` using Terraform 0.13.

I'm happy to clean up, add tests and create a pull request, but first wanted to ask if the approach is ok, or if there's something I'm missing. Thanks!

**Comment by dcaponi** [comment]
Hey! Yes I'm aware that 0.13 changes up some things and I had those fixes planned on my roadmap, and then some priorities changed (c'est la vie 😅 ) 

Anyway, these changes look like they'd work out fine. My primary concern is backward compatibility. Some of our users might be pretty slow to upgrade and it would be a shame if this stopped working for them. Would you mind confirming if this change still supports 0.12? If not I think we can come up with ways to detect the latest version (or ask in a prompt) and do whatever is needed to support each case.

Also you're saying the names of resources are not working? I remember appending the resource id to the name of the resource for the exact reason you describe with duplicate names so for example you should see `resource onelogin_apps my_app-1234` if I remember correctly... although it wouldn't surprise me if that got revved out somewhere.

Could you please send me an example of the main.tf file that comes out of your workaround so I have a better understanding of what the final product looks like? I assume you're just adding the new terraform provider stanza and other minor changes.

**Comment by jbauers** [comment]
Sure! Here's an example of the `main.tf` after my changes:

```
terraform {
	required_providers {
		onelogin = {
			source = "onelogin/onelogin"
		}
	}
}

provider onelogin {
	alias = "onelogin"
}

resource onelogin_apps _3_denmark_34 {
	allow_assumed_signin = false
	name = "3 Denmark"
	notes = ""
	visible = true

	provisioning = {
		enabled = false
	}

	parameters {
		safe_entitlements_enabled = false
		skip_if_blank = false
		user_attribute_mappings = "none"
		default_values = ""
		include_in_saml_assertion = false
		param_key_name = "password"
		user_attribute_macros = ""
		values = ""
		attributes_transformations = "none"
		label = "Password"
		provisioned_entitlements = false
	}

	connector_id = 12345
	description = ""
}

...
```

I'll try and confirm things still work with 0.12. Regarding the app naming, looks like things got lost [in this commit](https://github.com/onelogin/onelogin/commit/225221b3cd86e05d1fd35b5a318fbedd4cdf5bc7#diff-7384ee4a2c85c902f0e793a0019dea8d2c14cdbb40cf673ebf2548e1039ad4bf).


I'll split up those changes into separate PRs, so you can get the app naming fix in before tackling 0.13 :smiley:

**Comment by dcaponi** [comment]
Oh man, I definitely remember that refactor too. I looked at the associated PR and it looks good so I'll merge that.

Your TF output looks pretty much like the 0.12 output except for that new stanza they added. I think it might be redundant for 0.12 users but the addition of it doesnt seem to break for me and Im on:

```terraform --version
Terraform v0.12.24
+ provider.onelogin v0.1.1```

If it works for you on 0.13 then I think its good enough to merge.

**Comment by dcaponi** [comment]
Hey @jbauers I just published an update for this to include the required_providers stanza and work with Terraform v0.13+ 

You can check it out at [version v0.1.6](https://github.com/onelogin/onelogin/releases/tag/v0.1.6)

Could you please remind me if this issue still needs to be open? Looks like we merged some code and just need to close this out if you're all squared away. 😄

**Comment by jbauers** [comment]
Hey @dcaponi, sorry for the radio silence. I just took it for a spin, and it just works. I can run `onelogin terraform-import onelogin_apps` and afterwards `terraform plan` with no issues (I'm on Terraform v0.13.5). Thanks a lot, I'll close this issue!
